// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quiz335.Data;

namespace Quiz335.Migrations
{
    [DbContext(typeof(WebAPIQuiz335DBContext))]
    partial class WebAPIQuiz335DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("Quiz335.Models.Course", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("End1")
                        .HasColumnType("TEXT");

                    b.Property<string>("End2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Start1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Start2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Weekday1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Weekday2")
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Quiz335.Models.Enrolement", b =>
                {
                    b.Property<string>("EnrolementNum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Course")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentID")
                        .HasColumnType("INTEGER");

                    b.HasKey("EnrolementNum");

                    b.ToTable("Enrolements");
                });

            modelBuilder.Entity("Quiz335.Models.Marks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("A1")
                        .HasColumnType("REAL");

                    b.Property<float>("A2")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Marks");
                });

            modelBuilder.Entity("Quiz335.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("Quiz335.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
